version: "3.5"
services:
  rabbit:
    image: rabbitmq:latest
    networks:
      - greenhouse
  postgres:
    image: postgres:latest
    networks:
      - greenhouse
    volumes:
      - ./posgresql/data:/var/lib/postgres/data
  ph_server:
    build: .
    networks:
      - greenhouse
    volumes:
      - .:/code
    depends_on:
      - rabbit
    command: "./start.sh"

networks:
  greenhouse:
    external: True
    name: greenhouse
